name: Deploy ASV Online to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build static site
        run: node build.mjs

      # Debug: see what we built (leave in for now; remove later if you want)
      - name: Inspect dist
        run: |
          echo "--- dist file count ---"
          find dist -type f | wc -l
          echo "--- root ---"
          ls -lah dist | sed -n '1,200p'
          echo "--- sample verse dir ---"
          ls -lah dist/asv/Genesis/1/ | sed -n '1,200p' || true
          echo "--- head of index.html ---"
          sed -n '1,50p' dist/index.html || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Add CNAME
        run: echo "asv.the-holy-bible.livingwordbibles.com" > dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
